using System.ComponentModel.DataAnnotations;

namespace API.Dtos
{
    public class CartDto
    {
        [Required]
        public string Id { get; set; } // not saved in DB but will generated by client (Angular app)
        public List<CartItemDto> Items { get; set; }
        public int? DeliveryMethodId { get; set; }
        public string ClientSecret { get; set; }
        public string PaymentIntentId { get; set; }
    }
}