using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Entities
{
    public class Cart
    {
        public Cart()
        {
            // to use it for Redis witout need of parameter
        }

        public Cart(string id)
        {
            Id = id;
        }

        public string Id { get; set; } // not saved in DB but will generated by client (Angular app)
        public List<CartItem> Items { get; set; } = new List<CartItem>();


    }
}